name: Dev PR Test
 
on:
  pull_request:
    branches: [ main ]
 
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      ## git ignore에 등록된 application.properties 파일 생성해주기
      - name: make ENV
        run: |
          mkdir src/test/resources
          echo "${{ secrets.APPLICATION_YML_TEST }}" > ./src/test/resources/application.yml
        shell: bash
 
      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test
